### ISSUE TITLE
attempted relative import with no known parent package

### ISSUE THREAD

**Issue by ccycv** [HeinleinSupport/check_mk_extensions#105]
Any idea why I get this error?

Traceback (most recent call last):
  File "/usr/lib/check_mk_agent/plugins/./wireguard.py", line 18, in <module>
    from .agent_based_api.v1.type_defs import (
ImportError: attempted relative import with no known parent package

**Comment by gurubert** [comment]
You cannot put the check plugin into the agent plugin path.

The agent plugin is available at $OMD_ROOT/local/share/check_mk/agents/plugins
