### ISSUE TITLE
APC SLAVE Hosts are critical

### ISSUE THREAD

**Issue by Delido** [HeinleinSupport/check_mk_extensions#108]
https://github.com/HeinleinSupport/check_mk_extensions/blob/e25d5bc41dc84fde772e869799198e112c65b621/apcaccess/lib/check_mk/base/plugins/agent_based/apcaccess.py#L124

should be:
if data.get('STATUS') != 'ONLINE' and data.get('STATUS') != 'ONLINE SLAVE' and data.get('SELFTEST') == 'NO':

so you can check also if SLAVE Hosts have connection to master

**Comment by Delido** [comment]
also APC not working anymore in checkmk 2.1
TypeError (check_temperature() missing 1 required keyword-only argument: 'value_store')
  File "/omd/sites/check/local/lib/python3/cmk/base/plugins/agent_based/apcaccess.py", line 163, in check_apcaccess_temp
    yield from temperature.check_temperature(float(itemp[0]),

**Comment by gurubert** [comment]
second issue is fixed with commit ad571dfd4ce3e7eacbcf4252ea43f756dfd8591a
