### ISSUE TITLE
rspamd mkp generic approach

### ISSUE THREAD

**Issue by TonyBostonTB** [HeinleinSupport/check_mk_extensions#111]
With the actual script, the check wouldn't work on e.g. OpenBSD.
In this case 'pidof' is not known to openbsd and I had to comment out the tst for a rspamd PID so that it works.

Would it be possible to make that check more generic?

**Comment by gurubert** [comment]
How would such a generic code look like?
I have no *BSD system at hand. How do you test for a running process by name on *BSD?

**Comment by TonyBostonTB** [comment]
On 22.08.10 02:45, Robert Sander wrote:
> How would such a generic code look like?
> I have no *BSD system at hand. How do you test for a running process by name on *BSD?
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/HeinleinSupport/check_mk_extensions/issues/111#issuecomment-1210428935
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>

The only thing I see is 'pgrep' but that would give you the 'pgrep' PID
as well when searching for rspamd
