### ISSUE TITLE
check_mk 2.1 support

### ISSUE THREAD

**Issue by agabellini** [HeinleinSupport/check_mk_extensions#115]
Hello,

just upgraded from 2.0 to 2.1, and I have this issue with amavis

ImportError: cannot import name 'perfometer_linear' from 'cmk.gui.plugins.views.perfometers' (unknown location)

I think the same solution as in #109 will fix it

Andrea

**Comment by gurubert** [comment]
which extension package does this refer to?

**Comment by agabellini** [comment]
I'm sorry, I am referring to the amavis extension

**Comment by gurubert** [comment]
This has already been fixed in version 4.4 of the extension package.

https://exchange.checkmk.com/p/amavis-1
