### ISSUE TITLE
Fehlende Anführungszeichen in Datei dir_size

### ISSUE THREAD

**Issue by mstruminski** [HeinleinSupport/check_mk_extensions#118]
Hallo
in https://github.com/HeinleinSupport/check_mk_extensions/blob/cmk2.1/dir_size/agents/plugins/dir_size
Fehlt bei
        /usr/bin/du -s $path

die Anführungszeichen um "$path"

**Comment by mstruminski** [comment]
Kann darüber auch Pfade mit Leerzeichen geprüft werden??

**Comment by mstruminski** [comment]
Und in Datei 
https://github.com/HeinleinSupport/check_mk_extensions/blob/a5e716daf94711e4adc0b8c2f9c87924cf90bd8c/dir_size/lib/check_mk/base/plugins/agent_based/dir_size.py

def parse_dir_size(string_table):
    section = {}
    for size, *parts in string_table:
        path=' '.join(parts)
        section[path] = int(size) * 1024
    return section
register.agent_section(
    name="dir_size",
    parse_function=parse_dir_size,
)

**Comment by gurubert** [comment]
Pfade mit Leerzeichen können nicht geprüft werden.
dir_size ist auch nichts, was produktiv eingesetzt werden sollte. Das ist mehr ein Beispiel, wie ein Agenten- und Checkplugin geschrieben werden kann.
