### ISSUE TITLE
Error "Invalid color specification '#-9f-9f-9f'" instead of Placement Groups graph

### ISSUE THREAD

**Issue by HenriWahl** [HeinleinSupport/check_mk_extensions#120]
Hi there,
out of a sudden we notice the error message `Invalid color specification '#-9f-9f-9f'` in the graphs of the service **Ceph Status** instead of displaying the Placement Groups graph - as seen at the attached image:

![Bildschirmfoto vom 2023-02-08 10-47-39](https://user-images.githubusercontent.com/2835065/217495713-e5e3c482-a826-498d-bb09-6e3540c12683.png)

We run Checkmk Enterprise Edition 2.1.0p18 with the ceph plugin 10.16.

Any hint?

**Comment by gurubert** [comment]
The color is auto-generated. Maybe there is an overflow?

**Comment by HenriWahl** [comment]
@gurubert so without overflow it should be something like `#9f9f9f`?

What is the base of this autogeneration - looks like it is meant to be predictable as the error is the same all the time?

Where is it calculated? Maybe an `abs()` would take the `-` away?

**Comment by HenriWahl** [comment]
@gurubert could you give me a hint where to look for the calculation of the color or is this something coming from Checkmk itself?

**Comment by gurubert** [comment]
This is the line where the color gets generated:

https://github.com/HeinleinSupport/check_mk_extensions/blob/cmk2.1/ceph/web/plugins/metrics/ceph.py#L129

In the end it looks like a bug in the indexed_color() function.

**Comment by HenriWahl** [comment]
Hi @LarsMichelsen - is this something which might happen to other graphs too if `indexed_color()` calculates negative results?

**Comment by gurubert** [comment]
Something is not working with indexed_color(), @LarsMichelsen:

```
>>> from cmk.gui.plugins.metrics.utils import indexed_color
>>> indexed_color(1, 38)
'21/a'
>>> indexed_color(2, 38)
'31/a'
>>> indexed_color(2, 56)
'31/a'
>>> indexed_color(55, 56)
'#-bf0000'
>>> indexed_color(54, 56)
'#-9f-9f-9f'
>>> indexed_color(53, 56)
'#00-7f-7f'
>>> indexed_color(52, 56)
'#-5f00-5f'
>>> indexed_color(51, 56)
'#-3f-3f00'
>>> indexed_color(48, 56)
'#200000'
>>> indexed_color(47, 56)
'46/b'
>>> indexed_color(0, 56)
'11/a'
>>> indexed_color(1, 56)
'21/a'
>>> indexed_color(57, 56)
'#0000-fe'
>>> indexed_color(49, 56)
'#000000'
>>> indexed_color(50, 56)
'#0000-1f'
>>> indexed_color(51, 56)
'#-3f-3f00'
>>> indexed_color(51, 100)
'#cece00'
>>> indexed_color(95, 100)
'#00-7-7'
>>> indexed_color(94, 100)
'#-200-2'
>>> indexed_color(93, 100)
'#020200'
```

I would expect that up to (56, 56) the function returns a proper color. But it seems to fail 6 indices before total.

**Comment by HenriWahl** [comment]
@gurubert thanks! This version works like a charm!

**Comment by jherbel** [comment]
Hi @gurubert, this werk fixes the issues with indexed_color: https://checkmk.com/werk/15662
Best, Jörg
