### ISSUE TITLE
sslcertificates - Configuring the agent plugin for Windows is weird

### ISSUE THREAD

**Issue by robin-tribe29** [HeinleinSupport/check_mk_extensions#122]
When configuring the bakery rule for a Windows host, one has to provide a path, although the agent script does not even care about file system paths.

A quick fix would be to make the path argument in the bakery rule optional instead of mandatory.

**Comment by gurubert** [comment]
I really do not care about Windows :)

Maybe we add a little note that says that the path is only needed for Linux systems.

**Comment by robin-tribe29** [comment]
I am perfectly fine with that approach and a note would be helpful for sure.

My point is, however: You **have to** specify a path, otherwise you cannot save the rule.
Making that field optional and providing a note as you suggested would be awesome. :)
