### ISSUE TITLE
Service parameter overview buggy

### ISSUE THREAD

**Issue by doctore74** [HeinleinSupport/check_mk_extensions#125]
Directory Size Limits are working as expected.

The overview is buggy. (see screenshots)
![image](https://user-images.githubusercontent.com/18553498/234878258-21819f16-00b8-4578-961f-7204b8f0fb2b.png)

Tested in

- 2.0.0p31 (CME)
- Checkmk Managed Services Edition 2.1.0p24

**Comment by gurubert** [comment]
Please install the latest version. I see no such issue.
