### ISSUE TITLE
Fehlermeldung auf CheckMK Version 2.2.0p1

### ISSUE THREAD

**Issue by fabianhmg** [HeinleinSupport/check_mk_extensions#128]
Beim Import der *.mkp Datei:
Laden von "perfometer/kentix_devices" fehlgeschlagen: No module named 'cmk.gui.plugins.views.perfometers'

**Comment by gurubert** [comment]
has been fixed with commit 4fa6ea238b803ab38a216bbe44c9a2983fd6bf9e
