### ISSUE TITLE
ceph: Cluster services report absurd IO rates

### ISSUE THREAD

**Issue by jplitza** [HeinleinSupport/check_mk_extensions#129]
This is the actual output from a "Ceph Pool" service in our setup:

> IO: 151.74 Read IOPS, 110.25 Write IOPS, 202 KiB/s read, 102 MiB/s written
> IO: -17788150.81 Read IOPS, -13077624.78 Write IOPS, -22.6 GiB/s read, -11.6 TiB/s written
> IO: 8791344.65 Read IOPS, 6343623.96 Write IOPS, 11.2 GiB/s read, 5.57 TiB/s written

As you can see, the IO stats are reported three times - once for each ceph-mon in the cluster? I *guess* the first line is correct (simply because negative values and TiB/s on HDD seem unrealistic).

I guess the reason is that the CheckMK value store is associated to the cluster host, not the individual hosts. Hence, though the check is executed per-host, the I/O rate isn't necessarily calculated against the previous value from the same mon. And apparently, the cumulative values can differ between the mons.

**Comment by gurubert** [comment]
The checks are not cluster-enabled.

**Comment by jplitza** [comment]
https://github.com/HeinleinSupport/check_mk_extensions/blob/dc3cff5f79ca19cf05907c0e895ef76412452ae3/ceph/lib/check_mk/base/plugins/agent_based/cephdf.py#L129-L145

**Comment by gurubert** [comment]
Ups. :)

**Comment by gurubert** [comment]
I have now rewritten the cluster check function to only use the data from the first node. Please test.

**Comment by jplitza** [comment]
Nope, it still outputs negative values. Maybe the realistic values in the first line were only a coincidence.

OTOH, a quick experiment shows that the order of `list(dict.keys())` depends on the order of insertion into the dict (although the docs don't make any mention about the order at all, so that's probably not guaranteed either). My guess is that the order of the sections of the single hosts in the cluster section can vary, and so `list(section.keys())[0]` isn't guaranteed to always refer to the same host.

**Comment by gurubert** [comment]
Please test with MKP version 11.18.3

**Comment by jplitza** [comment]
Stats now look realistic and match what Ceph reports to InfluxDB. Thanks!
