### ISSUE TITLE
Infortrend Check werden nicht gefunden

### ISSUE THREAD

**Issue by KeksDipp** [HeinleinSupport/check_mk_extensions#130]
Ich versuche das Infotrend addon aus dem Repo zu verwenden. Es wird auch in Checkmk installiert und die Plugins werden erkannt ohne Fehlermeldung. Leider bekomme ich es nicht hin Daten aus dem Infotrend System auszulesen. Beim Discovery Prozess des Infotrend Systems wird lediglich der System Name angezeigt. 

Hat hier jemand einen Tipp für mich?

**Comment by gurubert** [comment]
Wahrscheinlich werden vom Infortrend SNMP-Agenten andere OIDs verwendet als die Check-Plugins kennen.

Bitte schick einmal einen SNMP-Walk vom Gerät. Dieser lässt sich über die Checkmk-GUI erzeugen. Das geht über das Action-Menü vom "Check_MK"-Servicecheck.

**Comment by JoGu01** [comment]
Hi,
bei mir das gleiche Problem.
Der SNMP-Walk scheint die falsche OID zu nehmen.
Meldung:

> Fetching 'walk'...
Failed: OID '.1.3.6.1.2.1.1.7.0': SNMP Error on 10.5.10.100: Timeout: No Response from 10.5.10.100 (Exit-Code: 1)
Job finished.

Muss man für die Checks noch irgendwas umkonfigurieren?
Nutze aktuell die 2.2.0p5-cre

Gruß,
Jörg

**Comment by gurubert** [comment]
> Failed: OID '.1.3.6.1.2.1.1.7.0': SNMP Error on 10.5.10.100: Timeout: No Response from 10.5.10.100 (Exit-Code: 1)

Das deutet eher darauf hin, dass die SNMP-Kommunikation als ganzes nicht funktioniert.
Die Credentials sind korrekt?

Dann kann es noch sein, dass der SNMP-Agent diese OID nicht zur Verfügung stellt. Checkmk kann das ignorieren, wenn es im Regelsatz "Hosts without system description OID" konfiguriert wird.

**Comment by JoGu01** [comment]
Hallo Robert,
nachdem ich jetzt "Hosts without system description OID" für das Storage gesetzt habe, ist der walk auch sehr viel länger.
An Services findet cmk leider nur "SNMP Info" und "Uptime".
Habe die Ausgabe vom walk mal angehängt.
[walk.txt](https://github.com/HeinleinSupport/check_mk_extensions/files/12024995/walk.txt)

**Comment by KeksDipp** [comment]
Hallo ich habe mich hier garnicht mehr zurückgemeldet. Bei mir waren zwei Probleme. Zum einen hat das Infotrend System sehr langsam geantwortet. Und zum anderen hat das Infotrend System nur SNMP v1 und v3 unterstützt. Nicht aber v2. Warum ist mir nicht so ganz klar. Da ich in Checkmk v2 & v3 für den Host konfiguriert hatte und das Secret angegeben hatte konnte nichts abgerufen werden. Da für SNMP v3 ein anderes Secret hinterlegt war. 

Mit dem umstellen auf v1 lief alles wie es soll. Es hat ebenfalls funktioniert auf SNMP v3 zu gehen wenn man den die Richtigen Credentials angibt. Außerdem habe ich die Timeout Zeit für den Host etwas hochgestellt.

Vielleicht hilft das ja auch bei dir. Bei mir nutze ich den Check mit einem Infotrend GS System. Auf DS Systemen ist es glaube ich aber ebenfalls so das nur v1 und v3 zur Verfügung stehen.

**Comment by gurubert** [comment]
Hi @JoGu01 ,

ich erhalte mit Deinem Walk alle Services in meiner Testinstanz.
