### ISSUE TITLE
Internal error: name 'Float' is not defined (V2.2.0)

### ISSUE THREAD

**Issue by DM-LUKAD** [HeinleinSupport/check_mk_extensions#134]
Hallo, 
nachdem ich das Plugin installiert habe, kann ich die "Other Services" nicht mehr aufrufen:

Meldung ..."Internal error: name 'Float' is not defined"...

![PLUGIN_ERROR](https://github.com/HeinleinSupport/check_mk_extensions/assets/47664571/7bc631b3-7466-445c-a06d-abbc09d06b66)

Ich benutze derzeit "Checkmk Enterprise Edition 2.2.0p3".
Vielen Dank für das gute Plugin!

**Comment by gurubert** [comment]
Um welches Plugin geht es denn?

**Comment by DM-LUKAD** [comment]
"check_snmp_metric"

https://github.com/HeinleinSupport/check_mk_extensions/tree/cmk2.2/check_snmp_metric

**Comment by DM-LUKAD** [comment]
THANK YOU ! WORKING !! 👍
