### ISSUE TITLE
Unknown parsing option passed to -P: 1

### ISSUE THREAD

**Issue by DM-LUKAD** [HeinleinSupport/check_mk_extensions#136]
Hallo, 
nochdem ich gestern die neue Version installiert habe, wollte ich diese direkt ausprobieren.
Leider bekomme ich nun eine Fehlermeldung "Unknown parsing option passed to -P: 1" (siehe Screenshots)

Vom Server aus bekomme problemlos die Metriken per snmpwalk.... 

![screen3](https://github.com/HeinleinSupport/check_mk_extensions/assets/47664571/47a20bb4-db2a-434a-83d4-218f8c50e334)

![screen2](https://github.com/HeinleinSupport/check_mk_extensions/assets/47664571/e9c05917-8fe1-4cd0-8c19-c1d6b15edce1)

![screen1](https://github.com/HeinleinSupport/check_mk_extensions/assets/47664571/b5502c11-9211-4fe7-a4d4-5e785779aa04)

**Comment by gurubert** [comment]
Ist in Verison 0.4.3 behoben.
