### ISSUE TITLE
Logic inverted for apcupsd output load metric

### ISSUE THREAD

**Issue by bduff-fl** [HeinleinSupport/check_mk_extensions#137]
![image](https://github.com/HeinleinSupport/check_mk_extensions/assets/96783161/9d1d43b0-47b5-4196-89a3-2a84fc319251)
As shown above, the logic is inverted. The WATO/Setup rule says that if load percent is *above* the specified values, however with these enabled, the service alarms for the current load percent being *below* the set thresholds.

**Comment by gurubert** [comment]
works as intended: https://github.com/HeinleinSupport/check_mk_extensions/blob/cmk2.2/apcaccess/lib/check_mk/base/plugins/agent_based/apcaccess.py#L100

If you enter a CRIT value lower than the WARN value the check logic checks lower bounds.
