### ISSUE TITLE
check_snmp/check_snmp_metric feature request

### ISSUE THREAD

**Issue by dnlldl** [HeinleinSupport/check_mk_extensions#138]
I have the following SNMP device:

```
1.3.6.1.4.1.39165.1.1.0 = "TV-IP1319PI" [ASN_OCTET_STR]
1.3.6.1.4.1.39165.1.2.0 = "0" [ASN_OCTET_STR]
1.3.6.1.4.1.39165.1.3.0 = "V5.5.3 build 200714" [ASN_OCTET_STR]
1.3.6.1.4.1.39165.1.4.0 = "3c-8c-f8-f7-f4-75" [ASN_OCTET_STR]
1.3.6.1.4.1.39165.1.5.0 = "88" [ASN_OCTET_STR]
1.3.6.1.4.1.39165.1.6.0 = "IPcamera" [ASN_OCTET_STR]
1.3.6.1.4.1.39165.1.7.0 = "26 PERCENT" [ASN_OCTET_STR]
1.3.6.1.4.1.39165.1.8.0 = "0.0 GB" [ASN_OCTET_STR]
1.3.6.1.4.1.39165.1.9.0 = "0 PERCENT" [ASN_OCTET_STR]
1.3.6.1.4.1.39165.1.10.0 = "512 MB" [ASN_OCTET_STR]
1.3.6.1.4.1.39165.1.11.0 = "60 PERCENT" [ASN_OCTET_STR]
1.3.6.1.4.1.39165.1.12.0 = "0" [ASN_INTEGER]
1.3.6.1.4.1.39165.1.13.0 = "10.2.1.11" [ASN_IPADDRESS]
1.3.6.1.4.1.39165.1.14.0 = "255.255.255.0" [ASN_IPADDRESS]
1.3.6.1.4.1.39165.1.15.0 = "10.2.1.1" [ASN_IPADDRESS]
1.3.6.1.4.1.39165.1.16.0 = "0.0.0.0" [ASN_IPADDRESS]
1.3.6.1.4.1.39165.1.17.0 = "0.0.0.0" [ASN_IPADDRESS]
1.3.6.1.4.1.39165.1.18.0 = "0.0.0.0" [ASN_IPADDRESS]
1.3.6.1.4.1.39165.1.19.0 = "2023-07-29 14:01:50" [ASN_OCTET_STR]
1.3.6.1.4.1.39165.1.20.0 = "1" [ASN_INTEGER]
1.3.6.1.4.1.39165.1.21.0 = "H.265" [ASN_OCTET_STR]
1.3.6.1.4.1.39165.1.22.0 = "H.265" [ASN_OCTET_STR]
1.3.6.1.4.1.39165.1.23.0 = "0" [ASN_INTEGER]
1.3.6.1.4.1.39165.1.24.0 = "0" [ASN_INTEGER]
1.3.6.1.4.1.39165.1.25.0 = "0" [ASN_INTEGER]
1.3.6.1.4.1.39165.1.26.0 = "1" [ASN_INTEGER]
1.3.6.1.4.1.39165.1.27.0 = "1" [ASN_INTEGER]
1.3.6.1.4.1.39165.1.28.0 = "1" [ASN_INTEGER]
1.3.6.1.4.1.39165.1.29.0 = "ETHERNET" [ASN_OCTET_STR]
1.3.6.1.4.1.39165.1.30.0 = "0" [ASN_INTEGER]
1.3.6.1.4.1.39165.1.31.0 = "0" [ASN_INTEGER]
1.3.6.1.4.1.39165.1.32.0 = "0.0.0.0" [ASN_IPADDRESS]
1.3.6.1.4.1.39165.1.33.0 = "10.2.1.1" [ASN_OCTET_STR]
1.3.6.1.4.1.39165.1.34.0 = "0" [ASN_INTEGER]
```
Is there any way to discover the whole 1.3.6.1.4.1.39165.1 tree and match the MIB names available such as here: https://mibs.observium.org/mib/HIK-DEVICE-MIB/

Rather than say create 34 different rules.

**Comment by gurubert** [comment]
No.

Please talk to the vendor of the device about how SNMP works.

**Comment by dnlldl** [comment]
> No.
> 
> Please talk to the vendor of the device about how SNMP works.

That would be Trendnet, and I probably have more chances to win the lotto than Trendnet to make any firmware change about SNMP ... ;-) especially about IP cameras, I'm lucky to have SNMP at all.

Just curious though, what makes you say this? They seem to follow the MIB correctly? I guess the best continuation path for me would be a custom plugin specifically for Trendnet camera devices. I was hoping they could be a way to make a general plugin to just find anything under a certain OID tree and match the values with MIB names.

**Comment by gurubert** [comment]
OIDs that end in .0 are only for SNMP get requests. Technically they fulfill the MIB, but the MIB was not designed well.

You would have to implement an SNMP check plugin that fetches all the single .0 OIDs and has their semantic meaning hardcoded. You can achieve the same by configuring a rule for check_snmp for each OID. In the end it is the same amount of work.

Please take this discussion to the checkmk forum if you have any further questions or remarks.

**Comment by dnlldl** [comment]
> You can achieve the same by configuring a rule for check_snmp for each OID. In the end it is the same amount of work.

Thanks for your help, I'm working on my own plugin and learning a lot from your code. I just want to point out however that having 34 independant active checks is **not** the same as parsing through the OIDs in one shot.
