### ISSUE TITLE
lancom_xdsl checkmk 2.2 compatibility

### ISSUE THREAD

**Issue by fuf42** [HeinleinSupport/check_mk_extensions#146]
The lancom_xdsl does not work in checkmk 2.2 as they changed something in utis.interfaces. 
The `get_traffic_levels `seem to have been replaced by `bandwidth_levels`
Any chance to get this working again?

**Comment by gurubert** [comment]
should be fixed with package version 0.3.0

**Comment by fuf42** [comment]
Thanks - it's working fine. But there is an upgrade issue. I had to add "CascadingDropdown" to the cmk.gui.valuespec import directive in plugins/wato/lancom_xdsl.py
