### ISSUE TITLE
BUG: entropy_avail package not built correctly

### ISSUE THREAD

**Issue by FelmeAn** [HeinleinSupport/check_mk_extensions#155]
Due to my last PR #147, the package was built new by @gurubert, but unfortunately we can't use the package, because it was built wrong. 

Error whilst adding: `tarfile.ReadError: not a gzip file`

**Comment by gurubert** [comment]
Please check if you really downloaded the MKP and not an HTML page.

**Comment by FelmeAn** [comment]
sorry. my fault - not using github as src-control (using self hosted gitlab). Was the wrong file data. 

OMD[cmk_pb_web]:/tmp$ file entropy_avail-5.2.4.mkp 
entropy_avail-5.2.4.mkp: JSON data
OMD[cmk_pb_web]:/tmp$ file entropy
entropy: gzip compressed data, last modified: Fri Jan 26 15:54:04 2024, max compression, original size modulo 2^32 61440


Thank you for your very, very fast support!
