### ISSUE TITLE
How does apachecount work?

### ISSUE THREAD

**Issue by dnlldl** [HeinleinSupport/check_mk_extensions#157]
Any chance to make this plugin compatible with 2.3 (if not already) and to provide some details on how to use it? I installed the MKP but there is no `.service` or script to deploy on the agent side.

**Comment by gurubert** [comment]
You have to install the files from the host folder (https://github.com/HeinleinSupport/check_mk_extensions/tree/cmk2.3/apachecount/host) on the monitored apache server host.
The script apachecount.py goes into /usr/sbin, the others go into /etc and its respective subdirectories.
The script apachecount.py has to be modified to filter the log lines that you are interested in.

It is a very customized extension and therefor not listed on the Checkmk Exchange for public use.
