### ISSUE TITLE
Plugin compatibility with CheckMK 2.3

### ISSUE THREAD

**Issue by mpibpc-mroose** [HeinleinSupport/check_mk_extensions#158]
Hi all,
I found at least two of your plugins incompatible with CheckMK v 2.3: `dell_omsa` and `infortrend` . Having this plugins installed makes updating to the newest version impossible,  I'm getting an error stating that an incompatible lokal check has been found ...

As I think this may apply to other MKPs, too I wanted to mak you aware about this ;-) Maybe you as experts can just explain what have to be done, the I will be glad to work togehter with you to make the plugins compatible again.

**Comment by belperite** [comment]
Yes I have the same with check_snmp

**Comment by mpibpc-mroose** [comment]
I wrote a [replacement](https://github.com/mpibpc-mroose/checkmk_plugin_infortrend) for the infortrend plugin. 

@gurubert do you want to "incorporate" this into the Heinlein checkmk-extensions? And as this is my first CheckMK plugin a review of my code would be highly appreciated...

**Comment by gurubert** [comment]
We have not started yet to migrate the extensions to 2.3. This is a task for the summer, when business is usually a little bit slower.

The old Dell OMSA and Infortrend extension will likely get no update as there are no systems and customers any more using these.

**Comment by jens-maus** [comment]
> The old Dell OMSA and Infortrend extension will likely get no update as there are no systems and customers any more using these.

Please note that I have just submitted a PR to introduce checkmk 2.3 compatibility for the infortrend plugin (see https://github.com/HeinleinSupport/check_mk_extensions/pull/161) and also slightly enhanced it a bit with added performance data and some more polishing here and there.
