### ISSUE TITLE
sslcertificates: Wrong link on exchange.checkmk.com

### ISSUE THREAD

**Issue by mueller-ma** [HeinleinSupport/check_mk_extensions#165]
The check `sslcertificates` on https://exchange.checkmk.com/p/sslcertificates has the link "website", which leads to this 404 page on an outdated repo: https://github.com/HeinleinSupport/check_mk_makanakoeln/tree/master/sslcertificates

**Comment by gurubert** [comment]
I am not able to correct the link on the exchange. Please direct your request to the Checkmk team.

**Comment by dnlldl** [comment]
The person with the account [rsander](https://exchange.checkmk.com/u/rsander) needs to update the link.

**Comment by gurubert** [comment]
As I am that person and as I have already written there is no possibility to change the URL for me.
