### ISSUE TITLE
sslcertificates: Add issuer as label

### ISSUE THREAD

**Issue by mueller-ma** [HeinleinSupport/check_mk_extensions#166]
Currently the plugin adds the issuer hash as label, which has two disadvantages:

1. As the issuer hash for let's encrypt changes from time to time (e.g. https://letsencrypt.org/2024/04/12/changes-to-issuance-chains.html), the rule for setting shorter WARN/CRIT has a growing number of hashes. With plain text issuers that list could become shorter by using regex and self-describing.
2. The hash doesn't work on Windows (also see https://github.com/HeinleinSupport/check_mk_extensions/issues/116#issuecomment-1381485095), so it's not possible to set different rules for different issuers.

Latter is required as let's encrypt are auto-renewed ~30 days before expiration, while others need manual renewal and 30 days might be too short for that.

**Comment by gurubert** [comment]
There is no source for the issuer name. Only the hash is available in a certificate.

**Comment by mueller-ma** [comment]
What do you mean by "no source"? Adding the issuer to the plugin output is possible on both Linux and Windows, see https://github.com/HeinleinSupport/check_mk_extensions/pull/167

**Comment by dnlldl** [comment]
This is kind of a problem for me too as the discoveries can give warnings for the label change when the hash is modified.

**Comment by mueller-ma** [comment]
The current label is the hash of the issuer name, which is generated by `openssl .... -issuer_hash ....` (https://docs.openssl.org/3.0/man1/openssl-x509/#certificate-printing-options). When it changes, the new issue label will change as well, but you get at least better feedback about it as it changes from (pseudocode) "some let's encrypt issuer" to "another let's encrypt issuer" and not from "'random' hash" to "another 'random' hash".
