### ISSUE TITLE
UPS Alarms - check failed - please submit a crash report!

### ISSUE THREAD

**Issue by domi-cloud** [HeinleinSupport/check_mk_extensions#168]
Hello,

we have installed the ups_alarms extension, though for multiple months the status of the service displays the message in the title.

Our versions:
MKP Version: 1.2
CMK Version: 2.3.0p9

Please let me know if you need more informations.
Thanks for response

**Comment by dnlldl** [comment]
If you go in the crash section of Checkmk monitoring, you will have more details on the exact error. Without that it's impossible to help.

![image](https://github.com/user-attachments/assets/e02f5e51-99dc-4cd7-9141-8d1042cc4a98)

Then you click on one of the report and you will have the exception with the complete traceback and the local variables. Ideally we need all 3.

You don't say which version of Checkmk you have (CRE, CEE, etc), that could help as well depending on the error.

With that being said, that plugin hasn't been updated in 3 years, I suspect its compatibility with Checkmk 2.3 might be problematic.

**Comment by domi-cloud** [comment]
> If you go in the crash section of Checkmk monitoring, you will have more details on the exact error. Without that it's impossible to help.
> 
> ![image](https://private-user-images.githubusercontent.com/32095302/368000508-e02f5e51-99dc-4cd7-9141-8d1042cc4a98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NTMyNDQsIm5iZiI6MTcyNjU1Mjk0NCwicGF0aCI6Ii8zMjA5NTMwMi8zNjgwMDA1MDgtZTAyZjVlNTEtOTlkYy00Y2Q3LTkxNDEtOGQxMDQyY2M0YTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDA2MDIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhOTIzZjBiZDJiYmUzNzkxZTRiYWYwZDZhMmRiNTk3NzhhMWUwMWIyNTI0ODI1OGYzZjc1MTJjZmUyODI1ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sr_Hf8zZhrCiMfaG4XVf_BXEqrnNFqvEDsicSwdOdII)
> 
> Then you click on one of the report and you will have the exception with the complete traceback and the local variables. Ideally we need all 3.
> 
> You don't say which version of Checkmk you have (CRE, CEE, etc), that could help as well depending on the error.
> 
> With that being said, that plugin hasn't been updated in 3 years, I suspect its compatibility with Checkmk 2.3 might be problematic.

Hi dnlldl,
thank you.
CMK Version CEE

![Screenshot 2024-09-17 081824](https://github.com/user-attachments/assets/f2391519-265f-447e-9a92-dee31affd914)

**Comment by gurubert** [comment]
Should be fixed in MKP version 1.2.1

**Comment by domi-cloud** [comment]
> Should be fixed in MKP version 1.2.1

Hey gurubert,
Thank you for the update!
There are still problems though but after all a different traceback. Maybe you can fix that too. Thanks in advance.

![{36C83726-93BD-4C6E-A99E-84A17A7A4860}](https://github.com/user-attachments/assets/8b5406a7-dfd5-4644-b2c5-aa0c9f9d091f)

**Comment by gurubert** [comment]
Your UPS seems to have a count greater than zero in the OID upsAlarmsPresent.

I have now changed the check logic to count the current alarms and not to rely on the counter.

**Comment by domi-cloud** [comment]
So it will work now?
So far I cannot see a new release on the checkmk exchange.

**Comment by domi-cloud** [comment]
> Your UPS seems to have a count greater than zero in the OID upsAlarmsPresent.
> 
> I have now changed the check logic to count the current alarms and not to rely on the counter.

So it will work now?
So far I cannot see a new release on the checkmk exchange.

**Comment by gurubert** [comment]
You can get the MKP from the git repo or wait until it has been published on the exchange.

**Comment by domi-cloud** [comment]
> You can get the MKP from the git repo or wait until it has been published on the exchange.

Got it, thank you. The service state is green now, but the UPS itself says there are four alarms present, when connecting to the web interface...

**Comment by gurubert** [comment]
Please send me the SNMP-Walk from that device. It can be retrieved via the action menu of the "Check_MK" service.

Maybe your device does not use the standard OIDs for its alarms.

**Comment by gurubert** [comment]
It looks like the ups_alarms check plugin is not for this type of UPS device.

It has 1 one at the OID UPS-MIB::upsAlarmsPresent.0 but nothing listed in the upsAlarmTable.

According to the UPS-MIB upsAlarmsPresent is "The present number of active alarm conditions.", therefor there should be one entry in upsAlarmTable.

When looking at the rest of the walk there is no obvious reference to 4 alarms. This would also be a new check plugin that has to be developed.

Therefor I close this case.
