### ISSUE TITLE
sslcertificates crashes after template change

### ISSUE THREAD

**Issue by mueller-ma** [HeinleinSupport/check_mk_extensions#174]
Exception in Checkmk: `ValueError ('\n' not allowed in 'summary')`

From agent output: 
````
<<<sslcertificates:sep(0)>>>
{<redacted>,"template":"Machine\r\n"} 
````

@elpepino89

**Comment by elpepino89** [comment]
It's weird that you have line breaks in template names, but I have added a workaround for that.

**Comment by JF-JX** [comment]
I have the same issue so it ain't that weird :P
Thank you!!
