### ISSUE TITLE
dell_sc

### ISSUE THREAD

**Issue by agabellini** [HeinleinSupport/check_mk_extensions#177]
Hello,

do you plan to port the plugin dell_sc to cmk 2.3?

Andrea

**Comment by agabellini** [comment]
Hello,

I just rewrote these plugins for version 2.3. If you are interested I can get them for you and if you want you can publish them in your repository

Andrea

**Comment by gurubert** [comment]
Hi Andrea,
could you please open a pull request?

**Comment by agabellini** [comment]
> Hi Andrea, could you please open a pull request?

Hello,

just opened a PR. I'm not very familiar with GitHub, so please bear with me if I messed up something.

Andrea

**Comment by gurubert** [comment]
Thanks, I have taken the code and rewrote it a little bit to put more logic into the parse_function.
