### ISSUE TITLE
check_imap don't work anymore with CheckMk 2.3.0 

### ISSUE THREAD

**Issue by 47k** [HeinleinSupport/check_mk_extensions#178]
After upgrade to 2.3.0 (from 2.2.0) I got this error on my IMAP services
```
sh: 1: $/check_imap: not found
```

**Comment by gurubert** [comment]
I am currently working on a migration to 2.3

**Comment by gurubert** [comment]
fixed with commit fd25053ac17b10c8674760b88bbef1a2843f4748
