### ISSUE TITLE
sslcertificates misses PEM files that contain multiple certificates

### ISSUE THREAD

**Issue by mayrstefan** [HeinleinSupport/check_mk_extensions#181]
We have some PEM files that contain multiple certificates. The plugin sslcertificates shows only the first certificate in those bundle files. All other certificates are skipped.

**Comment by gurubert** [comment]
This is a limitation of openssl and will not be fixed.

**Comment by mayrstefan** [comment]
I know that openssl only processes the first certificate. That's why I provided a PR to work around this limitation. My solution would be to feed the certificates to openssl individually if there are more than one.

Is this "won't fix" final or is there a chance that my PR (or the idea if it) finds it's way into the plugin?
