### ISSUE TITLE
[lancom_xdsl] Support for generic/non-lancom xDSL?

### ISSUE THREAD

**Issue by Commifreak** [HeinleinSupport/check_mk_extensions#183]
Hi,

I have a DrayTek Vigor 167 with SNMP enabled. It reports data via `1.3.6.1.2.1.10.94` and `1.3.6.1.2.1.10.251` (ADSL/VDSL MIB).
Is there any chance, that the lancom plugin could support non-lancom xDSL data?

There is an older plugin for those (https://github.com/f-zappa/check_mk_adsl_line) but it doesnt work with recent DrayTeks and the plugin work has stopped.

Thanks in advance!

**Comment by gurubert** [comment]
No, this will require a new check plugin.
