### ISSUE TITLE
jira_notifications not working with Check_MK 1.5.0p13

### ISSUE THREAD

**Issue by nbhatti** [HeinleinSupport/check_mk_extensions#48]
Hi, I am trying to use jira_notifications with Check_MK 1.5.0p13. Followed the documentation and have defined URL, Username, Password, Project ID and Issue type ID in Notification screen. But when a notification is generated, I don't see any call to Jira server. Enabled access_log on Jira server and don't see any request coming in from Check_MK. notifications log is only showing that rule matched and notification sent, but nothing gets received into Jira.

Since I am new to Python, any idea on where to look into troubleshoot and make this work with Jira?

Thanks.

**Comment by gurubert** [comment]
The notify.log from the site should provide some information.

**Comment by gurubert** [comment]
checkMK 1.6 comes with a builtin JIRA notification plugin.
I will discontinue my own version.

**Comment by nbhatti** [comment]
Sorry could not respond back earlier, it was the parameters issue which were not posting making the Python script to call the API without login/password.
