### ISSUE TITLE
Upstream extensions

### ISSUE THREAD

**Issue by ypid-geberit** [HeinleinSupport/check_mk_extensions#55]
Hey guys,

I am wondering, now that CheckMK supports pull requests at https://github.com/tribe29/checkmk, why not move the extensions there so that they ship with CheckMK? Wouldn’t it be beneficial to skip the searching and installing of extensions and just have CheckMKs auto inventory make it all work by default?

**Comment by ypid-geberit** [comment]
A short comment would be nice. At least the SNMP checks could be upstreamed because of the auto inventory, the other extensions that require some manual setup anyway bring less benefit. Can you understand my intention?

**Comment by gurubert** [comment]
The checkMK developers do not want the extra burden to support all and every extension. Some they will integrate but others not. It is their decision. And it is our decision if we want our extension to be upstreamed or not.

**Comment by ypid-geberit** [comment]
Thanks for explaining.
