### ISSUE TITLE
'df_translation' is not defined

### ISSUE THREAD

**Issue by agabellini** [HeinleinSupport/check_mk_extensions#64]
Hello,

just installed version 2.0 and I got this error:

CRIT: Loading "/omd/sites/site_name/local/share/check_mk/web/plugins/metrics/dell_sc.py" failed: name 'df_translation' is not defined (!!)

Thanks for this plugin!
Andrea

**Comment by vafhornung** [comment]
Hi Andrea,

i've updated my pull request #63 to fix this issue, waiting now for @gurubert to merge 😊

**Comment by agabellini** [comment]
Thank you!!!

**Comment by gurubert** [comment]
There is a new MKP (version 2.1) available.
