### ISSUE TITLE
Rspamd check: rrd errors

### ISSUE THREAD

**Issue by kokel** [HeinleinSupport/check_mk_extensions#67]
Hi there,
we are using your rspamd check (0.4/branch cmk1.6), thanks for this!
But at our cmk Installation (CheckMK Raw 1.6.0p14) the rrd graphs only show an traceback error.
Is it possible that this check works only for the Enterprise Edition?
Link to rrd error screenshots: https://cloud.s-v.de/index.php/s/LIwV3HEm9bSl4Ez
PW: rspamd
Thanks in advance!

**Comment by kokel** [comment]
For reference, there's also a thread in the checkmk forum: https://forum.checkmk.com/t/rspamd-graphs-not-working/18871

**Comment by kokel** [comment]
@gurubert, do you have any hints to solve this issue?

**Comment by gurubert** [comment]
No, sorry. The graphing system of the raw edition is still PNP4Nagios which is quite old. CRE 2.0 will have (parts of) the enterprise graphing system and this issue will resolve itself.

**Comment by kokel** [comment]
Turned out, that the problem is "stacked" in the graph_info sections.
This has to be "stack". Don't know if this change would be a problem for the enterprise graphing system, I would assume that it isn't.
