### ISSUE TITLE
rspamd check fails, when there are no mails scanned

### ISSUE THREAD

**Issue by jsjhb** [HeinleinSupport/check_mk_extensions#71]
If there are no mails scanned, rspamc does not output the dict "actions", hence the check fails.
Added test for existing "actions" section in info.
Additionally, if there are no mails scanned, "total" remains 0, which fails the rate calculation later (division by zero).

Added pull request #70

**Comment by gurubert** [comment]
The issue is fixed in the rspamd extension for checkmk 2.0
