### ISSUE TITLE
sslcertificates: compatibility with checkmk 2

### ISSUE THREAD

**Issue by Nothing4You** [HeinleinSupport/check_mk_extensions#73]
```
Loading GUI plugins...
Failed to load plugin /omd/sites/mysite/local/share/check_mk/web/plugins/wato/check_parameters_sslcertificates.py: __init__() got an unexpected keyword argument 'min_len'
Traceback (most recent call last):
  File "/omd/sites/mysite/lib/python3/cmk/gui/utils/__init__.py", line 164, in load_web_plugins
    exec(f.read(), globalvars)
  File "<string>", line 28, in <module>
TypeError: __init__() got an unexpected keyword argument 'min_len'

ERROR: Failed to load some GUI plugins. You will either have
       to remove or update them to be compatible with this
       Checkmk version.
```

removing the `min_len` parameter from https://github.com/HeinleinSupport/check_mk_extensions/blob/dbbcac92ac4f328cc060995c4adc58d2b8ffdd6a/sslcertificates/web/plugins/wato/check_parameters_sslcertificates.py#L28 is a workaround

I'm not sure if this is a result of this but it also failed to migrate the configuration for me when updating from checkmk 1.6.0p19

Another note:
https://exchange.checkmk.com/p/sslcertificates links to https://github.com/HeinleinSupport/check_mk/tree/master/sslcertificates which does not exist anymore, instead it should link to https://github.com/HeinleinSupport/check_mk_extensions/tree/master/sslcertificates/

**Comment by gurubert** [comment]
The repo has a branch cmk2.0 where sslcertificates has already been ported.
