### ISSUE TITLE
sslcertificates and checkmk 2.0

### ISSUE THREAD

**Issue by FJerusalem** [HeinleinSupport/check_mk_extensions#81]
Currently getting the following errors with v7.2 installed under checkmk 2.0p1

Starting job...
  WARNING: Exception in discovery function of check plugin 'sslcertificates': unexpected type in discovery: <class 'cmk.base.check_api_utils.Service'>
Completed.

Also config-settings in WATO not available.

**Comment by gurubert** [comment]
This repo has a branch called "cmk2.0" where the extensions are ported.
