### ISSUE TITLE
Ceph 9.3 for Checkmk 1.6 - is there still a general overview possible?

### ISSUE THREAD

**Issue by HenriWahl** [HeinleinSupport/check_mk_extensions#84]
Hi there,

after updating to the latest Ceph plugin 9.3 for Checkmk 1.6 I found that now every single node shows its Ceph information. Before it was available at the Ceph admin host which was a pretty clear overview.

Is this behaviour somehow achievable with the current version of the extension too?

Thanks anyway and regards

**Comment by gurubert** [comment]
OSDs should show at the hosts where they run. Pools and Status info on the hosts where MONs are running.

**Comment by HenriWahl** [comment]
OK thanks. Now mor informative than before :+1:
