### ISSUE TITLE
Missing import

### ISSUE THREAD

**Issue by yvanarnaud** [HeinleinSupport/check_mk_extensions#85]
Hi,
there is a missing import before or after following line:
https://github.com/HeinleinSupport/check_mk_extensions/blob/b96bd3b4f1db6efe57df2f6634df2933dc712326/netifaces/web/plugins/wato/netifaces.py#L19

`HostRulespec` is missing (used by `discovery_rbl_rules`).

Best regards

**Comment by gurubert** [comment]
fixed in commit e62f206b313c7c7c97f568d0dd34b6034f816610
