### ISSUE TITLE
 hpsa-8.1 agents/plugins/hpsa no output on HPE ProLiant DL360 Gen10

### ISSUE THREAD

**Issue by Y0d0g** [HeinleinSupport/check_mk_extensions#92]
Hallo Robert,

Auf einem neuen HPE Server (es ist witzigerweise der checkmk server selbst)
findet das hpsa agent plugin den Raid Controller nicht:

```
$ bash -x /omd/sites/prod/local/share/check_mk/agents/plugins/hpsa
+ '[' -e /proc/driver/cciss -o -e /sys/bus/cciss -o -e /sys/bus/pci/drivers/hpsa ']'
```
EOT

Aufruf von ssacli selbst liefert aber output, nur hat es keins der oben stehenden files/devices bei diesem Server.

```
$ ssacli controller all show config | grep -v '^$'
HPE Smart Array P408i-a SR Gen10 in Slot 0 (Embedded)  (sn: XXXXXXXXXXXXXXX)
   Internal Drive Cage at Port 1I, Box 1, OK
   Internal Drive Cage at Port 2I, Box 0, OK
   Port Name: 1I (Mixed)
   Port Name: 2I (Mixed)
   Array A (Solid State SATA, Unused Space: 1  MB)
      logicaldrive 1 (894.20 GB, RAID 5, OK)
      physicaldrive 1I:1:1 (port 1I:box 1:bay 1, SATA SSD, 480 GB, OK)
      physicaldrive 1I:1:2 (port 1I:box 1:bay 2, SATA SSD, 480 GB, OK)
      physicaldrive 1I:1:3 (port 1I:box 1:bay 3, SATA SSD, 480 GB, OK)
   SEP (Vendor ID HPE, Model Smart Adapter) 379  (WWID: XXXXXXXXXXXXXXXXX)
```

Ich frage mich, wie man wohl auf dem Server "erkennen" kann, dass ein  HPE Smart Array verbaut ist.
Das logical drive taucht im os als /dev/sda auf.

`strace -fe open ssacli ...` und `lspci` bringen mich auch noch nicht auf gute Ideen.

Hast Du eine Idee ?

**Comment by Y0d0g** [comment]
Kein hpsa modul mehr

```
$ lsmod | grep hp
hpilo                  17541  0 
hpwdt                  14536  0 
```

Vermutlich ist es jetzt das hier

```
$ lsmod | grep smartpqi
smartpqi               82097  2 
scsi_transport_sas     41224  2 ses,smartpqi

$ modinfo smartpqi | grep description:
description:    Driver for Microsemi Smart Family Controller version 1.2.10-099

$ cat /var/log/dmesg | grep Smart
[    4.357304] smartpqi 0000:b1:00.0: Microsemi Smart Family Controller found
[    4.607630] smartpqi 0000:b1:00.0: added 1:0:-:- xxxxxxxxxxxx  Enclosure         HPE      Smart Adapter    
```

Etwas mehr Info habe ich Dir noch per Email geschickt, danke!

**Comment by gurubert** [comment]
Bitte schreib im Agentenplugin die Zeile mit dem if um und ergänze um einen Test auf /sys/module/smartpqi

`if [ -e /sys/module/smartpqi -e  /proc/driver/cciss -o  -e /sys/bus/cciss -o -e /sys/bus/pci/drivers/hpsa ]; then`
