### ISSUE TITLE
Check remains in PEND

### ISSUE THREAD

**Issue by xmemy** [HeinleinSupport/check_mk_extensions#99]
Hey,

Installed version 5.6 + create all required rules for agent and service but all checks remain in PEND status (the service is stale, no data received within 1.5 check period)

The execution of the check in local works just fine (/usr/lib/check_mk_agent/plugins/memcached.py), parsing seems OK as well

`memcached                   127.0.0.1:8010 {'version': ('1.4.15', '1.4.15'), 'accepting_conns': 1, 'bytes_percent': (80, 90), 'evictions': (100, 200), 'cache_hit_rate': (20, 10), 'cas_badval': (5, 10), 'cmd_flush': (1, 5), 'listen_disabled_num': (5, 10), 'conn_yields': (1, 5), 'delete_misses': (1000, 2000), 'pointer_size': (64, 32)}                                                                                                      Memcached 127.0.0.1:8010`

Regards,

Vincent

**Comment by gurubert** [comment]
This is not the output of the agent plugin. It should look like this:

    <<<memcached>>>
    [10.192.0.166:11211]
    pid 63635
    uptime 697265
    time 1625648918
    version 1.5.6
    libevent 2.1.8-stable
    pointer_size 64
    rusage_user 631.077736
    rusage_system 948.393948
    max_connections 1024
    curr_connections 2
    total_connections 3346849
    rejected_connections 0
    connection_structures 32
    reserved_fds 20
    cmd_get 931205
    cmd_set 2799110
    cmd_flush 0
    cmd_touch 384360
    get_hits 868934
    get_misses 62271
    get_expired 17
    …

**Comment by xmemy** [comment]
Hey,

Found the issue, it's a dev server so we have several containers running memcached. I had to bind them on several loopback IP to have them working well (127.0.0.100, 127.0.0.101...)

Case can be closed.

Regards,

Vincent
